### ISSUE TITLE
failing with scss

### ISSUE THREAD

**Issue by jmonster** [lfridael/ember-cli-font-awesome#34] opened 2015-07-25 20:18 UTC
I believe I followed the instructions precisely, yet:

```sh
File: ~/tmp/tree_merger-tmp_dest_dir-DFPsBra7.tmp/app/styles/app.scss (3)
file to import not found or unreadable: font-awesome/path
Current dir: ~/tmp/tree_merger-tmp_dest_dir-DFPsBra7.tmp/app/styles/
```

context: 
```bash
DEBUG: Ember      : 1.13.3
DEBUG: Ember Data : 1.13.5
DEBUG: Firebase   : 2.2.7
DEBUG: EmberFire  : 0.0.0
DEBUG: jQuery     : 2.1.4
```

**Comment by lfridael** [comment] 2015-07-26 06:36
Without more info there's no way to tell if this is an ember-cli-font-awesome problem. it could very well be something with your ember-cli setup.

**Comment by null-null-null** [comment] 2015-07-27 19:05
We're experiencing this problem, too. Using the latest version of Ember CLI (1.13.1). What other information would you like?

**Comment by lfridael** [comment] 2015-07-28 05:38
A repo with an example app that reproduces the problem would help.

**Comment by null-null-null** [comment] 2015-07-28 17:44
Looks like the problem is that I was still using Brocfile.js. When I converted over to ember-cli-build.js, it worked fine. @jmonster Does that work for you, too?

**Comment by jmonster** [comment] 2015-07-29 02:28
no `Brocfile.js` here :(

**Comment by jmonster** [comment] 2015-07-29 02:49
@null-null-null do you have an example you can share of it working?

I'm also getting this deprecation warning, which seems strange considering I have no Brocfile:
```
Deprecation warning: sassOptions should be moved to your Brocfile
# ...
Error: file to import not found or unreadable: font-awesome/path
```

The later error is coming from:
```node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:276```

Here are (what I believe are) the interesting parts of my project:
ember-cli-build.js
```
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    // Add options here
    emberCliFontAwesome: {
      useScss: true
    }
  });

  // Use `app.import` to add additional libraries to the generated
  // output files.
  //
  // If you need to use different assets in different
  // environments, specify an object as the first parameter. That
  // object's keys should be the environment name and the values
  // should be the asset to use in that environment.
  //
  // If the library that you are including contains AMD or ES6
  // modules that you would like to import into your application
  // please specify an object with the list of modules as keys
  // along with the exports of each module as its value.

  return app.toTree();
};
```

app.scss
```scss
@import "settings";
@import "foundation";
@import "font-awesome/path";
```

bower.json
```json
"dependencies": {
    "ember": "1.13.3",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli/ember-cli-test-loader#0.1.3",
    "ember-data": "1.13.5",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.1",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "^2.1.4",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "qunit": "~1.17.1",
    "firebase": "^2.1.0",
    "ember-mocha": "~0.8.0",
    "foundation": "~5.5.0",
    "font-awesome": "4.4.0"
  }
}
```

package.json
```json
"devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "broccoli-clean-css": "1.0.0",
    "ember-cli": "1.13.1",
    "ember-cli-app-version": "0.4.0",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-divshot": "^0.1.7",
    "ember-cli-font-awesome": "0.1.0",
    "ember-cli-foundation-sass": "1.1.1",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.1.1",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-mocha": "0.9.1",
    "ember-cli-release": "0.2.3",
    "ember-cli-sass": "4.0.1",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.13.5",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.2",
    "emberfire": "firebase/emberfire#master",
    "torii": "0.5.1"
  }
```

**Comment by null-null-null** [comment] 2015-07-29 21:35
I could upload an example if it helps, but you can probably get it working by just creating a fresh app and installing ember-cli-font-awesome. I'm able to get that working over here.

**Comment by jmonster** [comment] 2015-07-30 07:05
1. Brand new ember cli app
2. Install/add this addon 
3. Rename app.css to app.scss, add the import line
4. Install/add ember-cli-sass

Running the server up to step 3 "works" without error. Of course, no CSS is being included on the page however.

As soon as k add the sass processor and attempt to import the aforementioned font-awesome/path I encounter the exact same errors previously described.

¯\_(ツ)_/¯

**Comment by lfridael** [comment] 2015-07-30 07:36
@jmonster The scss instructions contain an error.

The quickest way to get it working is to use this import in `app.scss`.

```
@import "bower_components/font-awesome/scss/font-awesome";
```

Personally, I don't use sass. There may be a more proper way of importing scss using include paths, but at least this gets you up and running.

**Comment by jmonster** [comment] 2015-07-30 16:40
ah, thank you :)

fwiw there exists some mechanism to make the original work because https://github.com/artificialio/ember-cli-foundation-sass uses a friendlier import:

```sass
@import "foundation"
```

I did a quick dig in that repo and it _may_ be [this line](https://github.com/artificialio/ember-cli-foundation-sass/blob/master/config/environment.js#L12) that makes it work:

```
appConfig.sassOptions.includePaths.push('bower_components/foundation/scss');
```

**Comment by lfridael** [comment] 2015-08-03 07:12
Closing this issue, as sass import seems to be working now.

**Closed by lfridael** 2015-08-03 07:12 UTC
